## 配置端口号
server:
  port: 8686

## 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/equipment?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useSSL=false&failOverReadOnly=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

## 配置 mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lly.equipment.entity

## 配置日志打印级别
logging:
  level:
    root: info
